# GopherTube Configuration File
# Copy this file to ~/.config/gophertube/gophertube.yaml and customize as needed

# Number of search results to fetch
# Default: 30 (lower it to increase speed)
search_limit: 30

